Repository hmcts/pre-api, pull requests merged in 2023-11, with the labels that each got.

#45 Add branch sync and slack build notifications
  Jenkinsfile_CNP
Labels: ns:pre, prd:pre, rel:pre-api-pr-45

#46 Add security label and rebase when behind master
  .github/renovate.json
Labels: ns:pre, prd:pre, rel:pre-api-pr-46

#58 S28 1939/flyway integration
  .github/workflows/ci.yml
  Jenkinsfile_CNP
  build.gradle
  charts/pre-api/Chart.yaml
  charts/pre-api/values.dev.template.yaml
  charts/pre-api/values.yaml
  docker-compose.yml
  docker/database/Dockerfile
  src/functionalTest/resources/application.properties
  src/integrationTest/java/uk/gov/hmcts/reform/preapi/config/FlywayConfigurationTest.java
  src/integrationTest/resources/application.properties
  src/main/java/uk/gov/hmcts/reform/preapi/config/FlywayConfiguration.java
  src/main/java/uk/gov/hmcts/reform/preapi/data/exception/PendingMigrationScriptException.java
  src/main/java/uk/gov/hmcts/reform/preapi/data/migration/FlywayNoOpStrategy.java
  src/main/resources/application.yaml
  src/smokeTest/resources/application.properties
Labels: ns:pre, prd:pre, rel:pre-api-pr-58, enable_helm_keep, enable_keep_helm

#68 Corrects KV value names
  charts/pre-api/Chart.yaml
  charts/pre-api/values.yaml
Labels: ns:pre, prd:pre, rel:pre-api-pr-68

#71 Schema
  src/main/resources/db/migrations/V001__CreateSchemaTables.sql
Labels: ns:pre, prd:pre, rel:pre-api-pr-71

#81 use debugging jenkins lib branch
  Jenkinsfile_CNP
Labels: ns:pre, prd:pre, rel:pre-api-pr-81

#82 Downgrade gradle flyway plugin to 9.x due to bug with migrations
  build.gradle
Labels: ns:pre, prd:pre, rel:pre-api-pr-82

#84 Remove unused dep and fix springdoc config for API spec generation
  build.gradle
  src/main/resources/application.yaml
Labels: ns:pre, prd:pre, rel:pre-api-pr-84
